# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: yarn
    command: |
      export HMR_HOST=`gp url 3000`
      echo 'setup your .env file then run yarn dev'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  
